export const red = '\x1b[31m%s\x1b[0m';
export const yellow = '\x1b[33m%s\x1b[0m';
export const green = '\x1b[32m%s\x1b[0m';
export const errorMessage = 'Operation failed';
export const errorPathMessage = 'Invalid path';
export const welcomeMessage = 'Welcome to the File Manager, ';
export const currentMessage = 'You are currently in';
export const thankMessage = 'Thank you for using File Manager, ';
export const farewellMessage = ',goodbye!:)';
